export { default as Home } from './home/home'
export { default as Login } from './login/login'
export { default as Register } from './register/register'
export { default as Private } from './private/private'
export { default as Dashboard } from './dashboard/dashboard'
export { default as NotFound } from './err/err'